# Generated by Django 5.2.7 on 2025-10-31 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions_app', '0002_rename_emissions_emission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50, unique=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emission_code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='emission',
            options={'ordering': ['-year']},
        ),
        migrations.AlterField(
            model_name='emission',
            name='activity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emission',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='emissions_app.country'),
        ),
        migrations.AlterField(
            model_name='emission',
            name='emission_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='emissions_app.emissiontype'),
        ),
        migrations.AlterUniqueTogether(
            name='emission',
            unique_together={('year', 'country', 'emission_type', 'activity')},
        ),
    ]
